name: Build and Push Backend Image to Docker Hub
run-name: "${{ github.actor }} is running for ECS"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-node-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            muraly26/node-image-app:latest
            muraly26/node-image-app:v1.0.${{ github.run_number }}


  build-react-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push React Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          build-args: |
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
          tags: |
            muraly26/react-image-app:latest
            muraly26/react-image-app:v1.0.${{ github.run_number }}


  deploy-to-ecs:
    runs-on: ubuntu-latest
    needs:
      - build-node-image
      - build-react-image

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test AWS Login
        run: aws sts get-caller-identity

      
      # Update backend image
      - name: Render backend container
        id: render-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nodecontainer
          image: muraly26/node-image-app:latest

      # Update frontend image
      - name: Render frontend container
        id: render-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-backend.outputs.task-definition }}
          container-name: reactcontainer
          image: muraly26/react-image-app:latest

       # Deploy
      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster git-cluster \
            --service gittask-service-ftwd9yhj \
            --force-new-deployment
 